### ISSUE TITLE
DU č.3

### ISSUE THREAD

**Issue by polko-irina** [polko-irina/Python-1#3]
Ahoj, dole posilám odkaz na bonus k úkolu č.2 

 https://github.com/polko-irina/Python-Czechitas/blob/master/2.%20lekce.%20DICT/5.du.py

A také mohu poprosit se podívat na úkol č. 3 nějak mi to nejde , nevím jak bych ověřila tu délku, mam použit funkci range()? nebo len()? 

Děkuji za odpověď

**Comment by polko-irina** [comment]
https://github.com/polko-irina/Python-Czechitas/blob/master/3.%20lekce%20FUNKCE/DU.py

**Comment by pmoravkova** [comment]
Bonus 2. - Vyborne!. 
Tip: Jen prosim, nepouzivej jako promennout dict nebo obecne jmena funkci, co jsou uz definovane, jako je prave dict, list, set, apod. Muze to pak v kodu udelat docela neplechu.

**Comment by pmoravkova** [comment]
Ukol 3:
jdes na to spravne, ono je to trosku nesikovne zadany, nebot overit cislo, k tomu je tolik moznosti, jak k tomu pristoupit. Nicmene tu se chce delka cisla zkontrolovat. Funkce range(x, y) ti vrati vsechna cisla v rozmezi od x do y. Ty tu chces ale kontrolovat delku pomoci, takze pouzijes len().
Cely ten kod ma vypadat tak, ze definujes dve funkce. Jednou overis, jestli zadane cislo ma 9 znaku, nebo 13 a zacina na +420. Druha se koukne na zpravu, a vypocte, kolikrat se tam vejde 180 znaku a vrati cenu te zpravy. Pak napises kod, ktery bude zadat input cislo telefonu, a pokud je cislo spravne, zepta se na zpravu, a vrati celkovou cenu. 
Pokud bys nevedela, muze zkusit doplnit tenhle mustr. Staci jen doplnit tu logiku do funkci:

```
def check_number(tel_number):
  # pokud je delka cisla devet nebo pokud je delka cisla 13 a zacina na +420
    return True
  else:
    return False

def message_price(message):
  price = # spocitej, kolik bude stat zprava
  return price

cislo = input('Zadej cislo: ')
if check_number(cislo):
  zprava = input('Zadej zpravu: ')
  print(f'Zprava bude stat {message_price(zprava)} Kc.')
else:
  print('Nespravne cislo.')
```

**Comment by polko-irina** [comment]
Ahoj, dole posilám odkaz na úkol č.3. Děkuji za radu :))

https://github.com/polko-irina/Python-Czechitas/blob/master/3.%20lekce%20FUNKCE/DU.py

**Comment by pmoravkova** [comment]
Super! presne tak! Dobra prace! Ukol mas odevzdany.
Ted budes moct ty funkce pouzit kdykoliv, nejen v tom kodu dole a vzdycky ti to vrati, kolik zprava bude stat. 
Tip:
Ve funkci nemusis mit na vsechno promennou, neni to nic proti nicemu, ale bohate by klidne stacilo: 
```
def cena_zpravy(massage):
    return (int((len(massage) / 180)) + 1 ) * 3
```
Zalezi pak uz jen na tobe, jak to chces mit prehledny, apod.
