### ISSUE TITLE
Úkol č.4 

### ISSUE THREAD

**Issue by polko-irina** [polko-irina/Python-1#4]
Ahoj, posilám dole odkaz na úkol č.4. Prosím tebe nejde mi tam přidat recept do listu, nevím kam mam napsat třídu Recept ?  

https://github.com/polko-irina/Python-Czechitas/blob/master/4.%20lekce%20OOP/5DU.py

Hezký den

**Comment by pmoravkova** [comment]
Ahoj. Trida recept je dobre. Super. 
Trida Kucharka:
ty tridu Recept nechces napojit na tridu Kucharka - kdybys chtela, tak to jde ruznymi zpusoby, dedicnost je jedna z nich. Ty zde vytvoris dve tridy, ktere o sobe navzajem nevi, a budes je 'spojovat', az v ramci kodu mimo tridy.
Seznam recepty je obycejny seznam, ktery vubec nevi, ze ho chces a budes zaplnovat necim z receptu. Proste seznam. Takze hned prvni funkce, tak nechces pridavat Recept(), tam proste jen nechas spocitat onen seznam recepty.
```
    def __str__(self):
        return (f'{self.nazev} od {self.autor} ma {self.recepty.count(Recept)} receptu.') # posledni {}, v ni spocitas list recepty {len(self.recepty)}
```
Funkce druha:
Doporucuju si vazne vsude davat printy, at sama vis, co ti to vraci. Hodne ti to pomuze i pochopit vic python apod.
Tvuj kod dela to, ze prochazi po jednom seznam recepty, a pak ti spocita count toho jednoho prvku v seznamu. Ty ale chces vedet, kolik prvku ma seznam recepty.
```
   def pocet_receptu(self):
        for i in self.recepty:
            self.recepty.count(i)
           # print(self.recepty.count(i)) - zkus si tohle sem doplnit a uvidis, co ti to bude vracet
```
Treti funkce:
Zde chces proste jen vytvorit funkci pridej_recept, ktera nebude delat nic jineho, nez jen prida prvek do seznamu. A te funkci je jedno, co tam pridas. Tuhle funkci musis prepracovat tak, aby proste to byla jen funkce, ktera pridava novy_recept do seznamu recepty. A az v kodu mimo tridu tam pridas ty dane recepty. 
```
   def pridej_recept(self, novy_recept):
        self.novy_recept = novy_recept # neni treba, ty tohle nechces prirazovat jakoze specificke pro tu danou kucharku, proto neni potreba davat self
        for novy_recept in self.recepty: # pozor! ty tady prepisujes promennou novy_recept, a prirazujes ji hodnotu ze seznamu recepty. Problem je, ze seznam je prazdny, proto ti to zde nic neprida
            self.recepty.append(novy_recept) # tohle je dobre a je to jediny radek, ktery vlastne potrebujes. Proste do seznamu pridas novy recept, ktery je argumentem funkce.
```
Vazne doporucuju zaplnit si to printy, kdyz to zkousis, abys videla, co ti jaka vec vraci.

**Comment by polko-irina** [comment]
Ahoj, posilám opravený kód , teď už jsem se zasekla na bonusu :)) koukni se prosím :)
Jinak úkol asi funguje správně :)) 

https://github.com/polko-irina/Python-Czechitas/blob/master/4.%20lekce%20OOP/5DU.py

Ještě prosím tebe chtěla bych aby i v tomto výpisu  return (f'{self.nazev} od {self.autor} ma {len(self.recepty)} receptu.')
se vypisovalo počet receptu přidaných v listu, ale furt to píše 0. Nevíš proč?  Ahoj

**Comment by pmoravkova** [comment]
Ahoj, nepise ti to furt nula, to pocita dobre a funguje to dobre. Ty zkousis vypsat ten radek predtim, nez tam cokoliv pridas a uz ne znovu.
```
dezerty = Kucharka('Dezerty', 'Iryny')
print(dezerty) # zde zkousis vyprintovat ten vypis, ale prozatim jsi jen classu iniciovala, takze seznam recepty je prazdny, takze nula ja v poradku.
dezerty.pridej_recept(muffiny) # tu pridavas teprv do seznamu. Kdyz zkusis vyprintovat dezerty po tomhle radku, tak uz tam budes mit jeden recept
print(dezerty) # tohle sem pridej a vrati ti to `Dezerty od Iryny ma 1 receptu.` Atd... 
dezerty.pridej_recept(tiramisu)
dezerty.pridej_recept(babovka)
print(dezerty.pocet_receptu()) # tady printujes tu nedokoncenou funkci, ktera ale vzdy vraci prazdny seznam. Takze to s poctem receptu nema vubec nic spolecneho (zatim. tak, jak je to napsany)

pernik = Recept('Pernik', 'hodně slozity', 'www.pernik.com')
dezerty.pridej_recept(pernik)
print(dezerty.pocet_receptu())
```
Funkce vyzkousene_recepty(), jak ji mas ted napsanou, je funkce, ktera ti vzdy zatim vrati prazdny seznam. takze kdyz zkousis `print(dezerty.pocet_receptu())`, tak ti to velmi spravne vypise []. Ale jdes na to dobre. Tohle jste delali na minulych hodinach, pouzijes normalni for cyklus. Vezmes prvek po prvku ze seznamu receptu, a pokud je vyzkouseno pravda, tak vysledek prihod do seznamu vyzkousene_recepty. To, na co jsi mozna narazila, a proc ti to nejde, je, ze ti ten senzam pak vypisuje neco na zpusob `[<__main__.Recept object at 0x7fa93d6ea4c0>]`, coz je ale dobre, protoze tohle je zpusob, jakym python ma v pameti zapsano objekt muffiny. Pokud chces, aby ti to python vracel v pro lidi citelne forme, tak mas nekolik moznosti - prvni je treba, ze do seznamu vyzkousene_recepty, budes v ramci append pridavat jen jednotlive komponenty receptu, napriklad nazev. Dalsi je, ze pouzijes ve tride Recept dle napovedy metodu `__repr__()`, ktera je obdobou metody `__str__()`, aneb vraci tadyten objekt ve stringove podobe.
```
   #zacatek i konec mas dobre, ted jen do toho prostoru hod for cyklus, ktery bude kontrolovat, zde vyzkouseno je pravda. 
   def vyzkousene_recepty(self):
        vyzkousene_recepty = []
        # if 
        #vyzkousene_recepty.append()
        return vyzkousene_recepty
```
Pomohlo? Pokud to neni jeste uplne jasne, tak muzu napovedet vic, nebo poslat pak i ten kod, jak prihodit __repr__ nebo tak.

**Comment by polko-irina** [comment]
Ahoj ten bonus stále nejde :(  i když včera se mi tohle vypisovalo  [<__main__.Recept object at 0x7fa93d6ea4c0>]. 
Jsem vymyslela něco takového ale to stejně nefunguje : ( 
https://github.com/polko-irina/Python-Czechitas/blob/master/4.%20lekce%20OOP/5DU.py

**Comment by pmoravkova** [comment]
Hazi ti to chybu: `TypeError: 'Recept' object is not iterable`, aneb ti to rika, ze objekt recept neni iterovatelny, coz dava smysl. Ale jdes na to dobre. Napisu ti to rovnou do kodu, ke kazde radce:

```
    def vyzkousene_recepty(self):
        vyzkousene_recepty = []
        for a in self.recepty:
            for self.nazev, self.narocnost, self.url_adresa, self.vyzkouseno in a: # zde chces prochazet polozkou recept, ale to je blbost, polozka recept neni iterovatelna. Tenhle radek uplne smaz, protoze bohate staci `if a.vyzkouseno:`
                if self.vyzkouseno: # tady pozor, tady mas self, coz znamena, ze to vztahujes k objektu ve tride kucharka, tery k te tve kucharce dezerty. Ale to ty nechces, ty se chces zeptat, jestli recept (muffiny, apod) jsou vyzkouseny. Takze namisto self das tu promennou, kterou sis v cyklu dosadila (a)
                    vyzkousene_recepty.append() # bacha, zde do seznamu nic nepridavas, musis mit v zavorce, co chces pridat
                return vyzkousene_recepty #a v neposledni rade pozor, return ukoncuje funkci. To znamena, ze jakmile to dojde k returnu, for cyklus dal nepokracuje.
```
Byla jsi hodne blizko, tak si to zkus kdyztak opravit, ale dolu ti napisu, jak by ta funkce mela vypadat, jedna z moznosti. A super pouziti __repr__(), chvalim.

```
    def vyzkousene_recepty(self):
        vyzkousene_recepty = []
        for a in self.recepty:
            if a.vyzkouseno:
                vyzkousene_recepty.append(a) # nebo muzes pridat jen nazev vyzkousene_recepty.append(a.nazev)
        return vyzkousene_recepty # a pak v hezcim vypisu to vypsat return f"Byly vyzkouseny recepty na {', '.join(vyzkousene_recepty)}"
```

**Comment by polko-irina** [comment]
Díky :)) Tady odevzdávám úkol č.4. 
https://github.com/polko-irina/Python-Czechitas/blob/master/4.%20lekce%20OOP/5DU.py
Hezký večer

**Comment by pmoravkova** [comment]
Super, diky. Doufam, ze je to uz jasnejsi.
