### ISSUE TITLE
DU Dědičnost

### ISSUE THREAD

**Issue by polko-irina** [polko-irina/Python-1#5]
Ahojky, posilám odkaz na úkol Dědičnost. Přidává mi tam do listu moje atributy místo toho aby to dělala funkce :(( což vůbec nechápu jak je to možní? a když napíšu  varianty sem tak se pak stejně nepřidávají do seznamu .

class Koronavirus(Nemoc):
    def __init__(self, jmeno, inkubacni_doba, pocet_obeti, sireni, varianty ):
        super().__init__(jmeno, inkubacni_doba, pocet_obeti, sireni)
        self.varianty = []

https://github.com/polko-irina/Python-Czechitas/blob/master/5.%20lekce%20D%C4%9Bdicnost/3.DU.py

Hezký den :))

**Comment by pmoravkova** [comment]
Ahoj, tohle nechapu, co tim uplne myslis: Přidává mi tam do listu moje atributy místo toho aby to dělala funkce.

Nicmene proc ti to nepridava funkce:
1. Mas tam preklep, a ve jmene pridej_variantu ti chybi t: `corona.pridej_variantu('omikron')` - proto ti to bude hazet error: "AttributeError: 'Koronavirus' object has no attribute 'pridej_varianu'"
2. Funkce pridej variantu, koukni se poradne na tu funkci, cos napsala:
```
    def pridej_variantu(self, varianta):
        for varianta in self.varianty: 
            self.varianty.append(varianta)
```
Ona ti projde seznam varianty (ktery v initu definujes jako prazdny seznam), prepise promennou varianta, kterou davas jako argument funkce, polozkou ze seznamu, a kazdou polozku z toho prazdneho seznamu, prida do stejneho seznamu. Takze na konci je prazdny seznam. Ty ale chces vzit ten seznam a pridat do nej variantu, ktera se da jako argument te funkce. takze jen self.varianty.apend(varianta)

**Comment by polko-irina** [comment]
Ahoj, děkuji za radu , odevzdávám úkol č.5 dědičnost.
https://github.com/polko-irina/Python-Czechitas/blob/master/5.%20lekce%20D%C4%9Bdicnost/3.DU.py
Hezký den :)

**Comment by polko-irina** [comment]
Ahoj, odevzdávám úkol č.7 Datum a Čas.
https://github.com/polko-irina/Python-Czechitas/blob/master/7.%20lekce/DU.py
Hezký den :)

**Comment by pmoravkova** [comment]
super prace! ukol odevzdany.
Tip:
Mas tam zbytecny import datetime, coz nevadi, jen kdybys resila pamet apod. Ale obecne v ramci standardu kodovani se snazi vyhnout zbytecnym importum.
