### ISSUE TITLE
Ukol 8

### ISSUE THREAD

**Issue by polko-irina** [polko-irina/Python-1#6]
Ahoj , posilám ke kontrole DU č. 8.  Hezký den :)
 
https://github.com/polko-irina/Python-Czechitas/blob/master/8.lekce/3.py

**Comment by polko-irina** [comment]
Ahoj , prosím tebe ještě úkol 9, jsem se zasekla na bonusu 2 : "Dotaz na řádky z 13. listopadu 2017 ze Spojených států amerických (sloupec Day musí mít hodnotu 13 a sloupec Country hodnotu US)"

 https://github.com/polko-irina/Python-Czechitas/blob/master/9.%20lekce/4DU.py

**Comment by pmoravkova** [comment]
8 mas v poradku. 9 mas tez odevzdanou, a co se tyce na te zaseknute radce, tam je potiz, ze tu podminku se snazis napasovat na dataframe. Ted nevim, jestli vysvetluju srozumitelne, ale ty udelas `temperature.loc['US']`, coz ti vrati dataframe, a pak udelas `temperature[temperature["Day"] == 13]`, coz ti tez vrati dataframe a mezi to das &. Jenze pomoci & se spojuje podminka, nejde tim spojit dataframy. Takze ty musis napsat tu podminku jinak, predtim nez z toho stvoris ten dataframe. Mas nekolik moznosti - bud country nebudes pouzivat jako index a pak to udelas, jako kdyz jsi vyhledavala teplotu v evrope nad 60 stupnu. Nebo nastavis jako index vic hodnot, takze do set_index das country i den, a pak pomoci locu muzes hledat vice veci `df.loc['US', 13]`. Nebo das se da jeste pouzit na den klasicka podminka, jako mas, a namisto `df.loc` pouzijes `df.index == hodnota`
